--liquibase formatted sql

--changeset SappyJoy:3
create table `USER`
(
    user_id         bigint generated by default as identity
        constraint users_pkey
            primary key,
    username      varchar(255),
    password   varchar(255)
);

create table `USER_ROLE`
(
    user_id bigint not null
        constraint fkhfh9dx7w3ubf1co1vdev94g3f
            references `USER` ON DELETE CASCADE,
    role_id bigint not null
        constraint fkhfh9dx7w3ubf1co1vdev94g4f
            references `ROLE` ON DELETE CASCADE
);

create table `ROLE`
(
    role_id         bigint generated by default as identity
        constraint role_pkey
            primary key,
    rolename      varchar(255),
);

