--liquibase formatted sql

--changeset ddzhukashev:1
create table users
(
    id         bigint generated by default as identity
        constraint users_pkey
            primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    status     varchar(255)
);

create table user_roles
(
    user_id bigint not null
        constraint fkhfh9dx7w3ubf1co1vdev94g3f
            references users ON DELETE CASCADE,
    roles   varchar(255)
);

