version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/portainer-data:/data
    ports:
      - "9000:9000"
  postgres_users:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: users_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - "./volumes/postgres_users:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: unless-stopped
  postgres_market:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: market_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - "./volumes/postgres_users:/var/lib/postgresql/data"
    ports:
      - "5433:5433"
    restart: unless-stopped
  shared_lib:
    container_name: shared_lib
    image: shared_lib
    build: ./shared_lib
  eureka-server:
    container_name: eureka-server
    image: eurekaserverimage
    build: ./eureka-server
    ports:
      - "8761:8761"
  config-service:
    image: configserviceimage
    container_name: config-service
    build: ./config-service
    ports:
      - "8762:8762"
    environment:
      PORT: 8762
      EUREKA_ADDRESS: "eureka-server:8761"
    depends_on:
      - eureka-server
#  user-service:
#    image: userserviceimage
#    container_name: user-service
#    build: ./user-service
#    ports:
#      - "8081:8081"
#    environment:
#      PORT: 8081
#      EUREKA_ADDRESS: "eureka-server:8761"
#      CONFIG_URL: "config-service:8762"
#      POSTGRES_ADDRESS: "postgres_users:5432"
#    deploy:
#      restart_policy:
#        condition: on-failure
#        max_attempts: 3
#    depends_on:
#      - config-service
#      - postgres_users
#      - shared_lib
#  auth-service:
#    image: authserviceimage
#    container_name: auth-service
#    build: ./auth-service
#    ports:
#      - "8082:8082"
#    environment:
#      PORT: 8082
#      EUREKA_ADDRESS: "eureka-server:8761"
#      CONFIG_URL: "config-service:8762"
#    deploy:
#      restart_policy:
#        condition: on-failure
#        max_attempts: 5
#    depends_on:
#      - postgres_users
#      - config-service
#      - user-service
#      - shared_lib
#  person-service:
#    image: personserviceimage
#    container_name: person-service
#    build: ./person-service
#    ports:
#      - "8083:8083"
#    environment:
#      PORT: 8083
#      EUREKA_ADDRESS: "eureka-server:8761"
#      CONFIG_URL: "config-service:8762"
#    deploy:
#      restart_policy:
#        condition: on-failure
#        max_attempts: 3
#    depends_on:
#      - config-service
#      - postgres_users
#      - shared_lib
#  content-service:
#    image: contentserviceimage
#    container_name: content-service
#    build: ./content-service
#    ports:
#      - "8084:8084"
#    environment:
#      PORT: 8084
#      EUREKA_ADDRESS: "eureka-server:8761"
#      CONFIG_URL: "config-service:8762"
#    deploy:
#      restart_policy:
#        condition: on-failure
#        max_attempts: 3
#    depends_on:
#      - config-service
#      - postgres_users
#      - shared_lib
#  card-service:
#    image: cardserviceimage
#    container_name: card-service
#    build: ./card-service
#    ports:
#      - "8085:8085"
#    environment:
#      PORT: 8085
#      EUREKA_ADDRESS: "eureka-server:8761"
#      CONFIG_URL: "config-service:8762"
#    deploy:
#      restart_policy:
#        condition: on-failure
#        max_attempts: 3
#    depends_on:
#      - config-service
#      - postgres_users
#      - shared_lib
  market-service:
    image: marketserviceimage
    container_name: market-service
    build: ./market-service
    ports:
      - "8086:8086"
    environment:
      PORT: 8086
      EUREKA_ADDRESS: "eureka-server:8761"
      CONFIG_URL: "config-service:8762"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - config-service
      - postgres_users
      - shared_lib
