spring:
  application:
    name: spring-gateway
  config:
    import: "optional:configserver:http://config-server:8888/"

springdoc:
  swagger-ui:
    use-root-path: true
  api-docs:
    enabled: true

eureka:
  instance:
    hostname: spring-gateway
